// This file is auto-generated by scripts/build-company-manifest.mjs. Do not edit by hand.
import company1 from "@/data/companies/amber-enterprises.json";
import company2 from "@/data/companies/dixon-technologies.json";
import company3 from "@/data/companies/mtar-technologies.json";

export const verifiedCompanyManifest = [
  { id: "amber-enterprises", data: company1 },
  { id: "dixon-technologies", data: company2 },
  { id: "mtar-technologies", data: company3 },
] as const;
