// This file is auto-generated by scripts/build-company-manifest.mjs. Do not edit by hand.
import company1 from "@/data/companies/amber-enterprises.json";
import company2 from "@/data/companies/dixon-technologies.json";
import company3 from "@/data/companies/hindustan-aeronautics-limited.json";
import company4 from "@/data/companies/modison-limited.json";
import company5 from "@/data/companies/mtar-technologies.json";
import company6 from "@/data/companies/ptc-industries-limited.json";

export const verifiedCompanyManifest = [
  { id: "amber-enterprises", data: company1 },
  { id: "dixon-technologies", data: company2 },
  { id: "hindustan-aeronautics-limited", data: company3 },
  { id: "modison-limited", data: company4 },
  { id: "mtar-technologies", data: company5 },
  { id: "ptc-industries-limited", data: company6 },
] as const;
